language: cpp
compiler:
  - gcc
  - clang
sudo: false
install:
  - echo ho
script:
  - return `expr $RANDOM % 2`

notifications:
  webhook:
    urls:
      - https://kmc-slack-webhook.herokuapp.com/travis
    on_success: change
    on_failure: always
